# Generated by Django 2.1.7 on 2019-03-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zadacha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opisanie', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Zaplanirovana', 'Zaplanirovana'), ('Vypolneno', 'Vypolneno'), ('Otmeneno', 'Otmeneno')], max_length=100)),
            ],
        ),
    ]
