# Generated by Django 2.1.7 on 2019-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('quote_author', models.CharField(max_length=255)),
                ('chytaty', models.CharField(choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow'), ('After three days', 'After three days')], max_length=100)),
            ],
        ),
    ]
